FROM python:3.8.3-slim-buster

LABEL maintainer="Sebastian Ramirez <tiangolo@gmail.com>"

RUN apt-get update && apt-get upgrade -y && \
    apt-get install --no-install-recommends -y gcc libgcc-8-dev libc6-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install meinheld gunicorn

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./start.sh /start.sh
RUN chmod +x /start.sh

COPY ./gunicorn_conf.py /gunicorn_conf.py

COPY ./app /app
WORKDIR /app/

ENV PYTHONPATH=/app

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]

# Run the start script, it will check for an /app/prestart.sh script (e.g. for migrations)
# And then will start Gunicorn with Meinheld
CMD ["/start.sh"]
